import { getAllInterviewReports, generateInterviewReport, getInterviewReportById, generateResumePdf } from "../services/interview.api"
import { useContext, useEffect } from "react"
import { InterviewContext } from "../interview.context"
import { useParams } from "react-router"


export const useInterview = () => {

    const context = useContext(InterviewContext)
    const { interviewId } = useParams()

    if (!context) {
        throw new Error("useInterview must be used within an InterviewProvider")
    }

    const { loading, setLoading, report, setReport, reports, setReports } = context

    const generateReport = async ({ jobDescription, selfDescription, resumeFile }) => {
        setLoading(true)
        let response = null
        try {
            response = await generateInterviewReport({ jobDescription, selfDescription, resumeFile })
            setReport(response.interviewReport)
        } catch (error) {
            console.log(error)
            alert(
                error?.response?.data?.error ||
                error?.message ||
                "Unknown Error"
            );
        } finally {
            setLoading(false)
        }

        return response ? response.interviewReport : null
    }

    const getReportById = async (interviewId) => {
        setLoading(true)
        let response = null
        try {
            response = await getInterviewReportById(interviewId)
            setReport(response.interviewReport)
        } catch (error) {
            console.log(error)
        } finally {
            setLoading(false)
        }
        return response.interviewReport
    }

    const getReports = async () => {
        setLoading(true)
        let response = null
        try {
            response = await getAllInterviewReports()
            setReports(response.interviewReports)
        } catch (error) {
            console.log(error)
        } finally {
            setLoading(false)
        }

        return response ? response.interviewReports : [];
    }

    const getResumePdf = async (reportData) => {
        if (!reportData?.resume) return;
        
        setLoading(true)
        try {
            const { jsPDF } = await import('jspdf');
            const doc = new jsPDF('p', 'mm', 'a4');
            const pageWidth = doc.internal.pageSize.getWidth();
            const margin = 20;
            const contentWidth = pageWidth - (margin * 2);
            let yPos = 25;

            // --- 1. Header with Gradient-like effect ---
            doc.setFillColor(31, 41, 55); // Dark Slate
            doc.rect(0, 0, pageWidth, 45, 'F');
            
            doc.setTextColor(255, 255, 255);
            doc.setFont("helvetica", "bold");
            doc.setFontSize(24);
            doc.text("CURRICULUM VITAE", margin, 22);
            
            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.text("Tailored for: " + (reportData.title || "Target Role"), margin, 32);
            doc.text("Generated by InterviewIQ AI", margin, 38);

            // --- 2. Main Content ---
            yPos = 60;
            doc.setTextColor(31, 41, 55);
            
            const addSection = (title, content) => {
                if (!content) return;
                
                // Section Title
                doc.setFont("helvetica", "bold");
                doc.setFontSize(14);
                doc.text(title.toUpperCase(), margin, yPos);
                
                // Underline
                doc.setDrawColor(209, 213, 219);
                doc.line(margin, yPos + 2, pageWidth - margin, yPos + 2);
                
                yPos += 10;
                
                // Section Content
                doc.setFont("helvetica", "normal");
                doc.setFontSize(11);
                const lines = doc.splitTextToSize(content, contentWidth);
                
                // Check for page overflow
                if (yPos + (lines.length * 6) > 280) {
                    doc.addPage();
                    yPos = 25;
                }
                
                doc.text(lines, margin, yPos);
                yPos += (lines.length * 6) + 10;
            };

            // Parse resume into basic sections if possible (simplified for AI output)
            addSection("Professional Summary", reportData.selfDescription || "Executive professional with a strong track record of success.");
            addSection("Detailed Background", reportData.resume);
            
            // Add a "Key Strengths" section based on the match
            if (reportData.skillGaps) {
                const skillsText = reportData.skillGaps.map(g => g.skill).join(", ");
                addSection("Relevant Expertise", skillsText);
            }

            doc.save(`Professional_Resume_${reportData._id?.substring(0, 5) || 'IQ'}.pdf`);
        }
        catch (error) {
            console.log("PDF Error:", error)
            alert("Failed to generate professional PDF. Please try again.")
        } finally {
            setLoading(false)
        }
    }

    useEffect(() => {
        getReports()
    }, [])

    useEffect(() => {
        if (interviewId) {
            getReportById(interviewId)
        }
    }, [ interviewId ])

    return { loading, report, reports, generateReport, getReportById, getReports, getResumePdf }

}