import { getAllInterviewReports, generateInterviewReport, getInterviewReportById, generateResumePdf } from "../services/interview.api"
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { useParams, useNavigate } from "react-router"

export const useInterview = () => {
    const { interviewId } = useParams()
    const queryClient = useQueryClient()
    const navigate = useNavigate()

    const { data: report, isLoading: isReportLoading } = useQuery({
        queryKey: ['interview', interviewId],
        queryFn: async () => {
            const response = await getInterviewReportById(interviewId)
            return response.interviewReport
        },
        enabled: !!interviewId,
        refetchInterval: (query) => {
            const data = query.state?.data;
            if (data?.status === 'pending' || data?.status === 'processing') {
                return 3000; // Poll every 3s
            }
            return false;
        }
    })

    const { data: reports, isLoading: isReportsLoading } = useQuery({
        queryKey: ['interviews'],
        queryFn: async () => {
            const response = await getAllInterviewReports()
            return response.interviewReports
        }
    })

    const generateMutation = useMutation({
        mutationFn: async ({ jobDescription, selfDescription, resumeFile }) => {
            const response = await generateInterviewReport({ jobDescription, selfDescription, resumeFile })
            return response.interviewReport
        },
        onSuccess: (data) => {
            queryClient.invalidateQueries({ queryKey: ['interviews'] })
        },
        onError: (error) => {
            console.log(error)
            alert(
                error?.response?.data?.error ||
                error?.message ||
                "Unknown Error"
            );
        }
    })

    const getResumePdf = async (reportData) => {
        if (!reportData?.resume) return;
        
        try {
            const { jsPDF } = await import('jspdf');
            const doc = new jsPDF('p', 'mm', 'a4');
            const pageWidth = doc.internal.pageSize.getWidth();
            const margin = 20;
            const contentWidth = pageWidth - (margin * 2);
            let yPos = 25;

            // --- 1. Header with Gradient-like effect ---
            doc.setFillColor(31, 41, 55); // Dark Slate
            doc.rect(0, 0, pageWidth, 45, 'F');
            
            doc.setTextColor(255, 255, 255);
            doc.setFont("helvetica", "bold");
            doc.setFontSize(24);
            doc.text("CURRICULUM VITAE", margin, 22);
            
            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.text("Tailored for: " + (reportData.title || "Target Role"), margin, 32);
            doc.text("Generated by InterviewIQ AI", margin, 38);

            // --- 2. Main Content ---
            yPos = 60;
            doc.setTextColor(31, 41, 55);
            
            const addSection = (title, content) => {
                if (!content) return;
                
                // Section Title
                doc.setFont("helvetica", "bold");
                doc.setFontSize(14);
                doc.text(title.toUpperCase(), margin, yPos);
                
                // Underline
                doc.setDrawColor(209, 213, 219);
                doc.line(margin, yPos + 2, pageWidth - margin, yPos + 2);
                
                yPos += 10;
                
                // Section Content
                doc.setFont("helvetica", "normal");
                doc.setFontSize(11);
                const lines = doc.splitTextToSize(content, contentWidth);
                
                // Check for page overflow
                if (yPos + (lines.length * 6) > 280) {
                    doc.addPage();
                    yPos = 25;
                }
                
                doc.text(lines, margin, yPos);
                yPos += (lines.length * 6) + 10;
            };

            // Parse resume into basic sections if possible (simplified for AI output)
            addSection("Professional Summary", reportData.selfDescription || "Executive professional with a strong track record of success.");
            addSection("Detailed Background", reportData.resume);
            
            // Add a "Key Strengths" section based on the match
            if (reportData.skillGaps) {
                const skillsText = reportData.skillGaps.map(g => g.skill).join(", ");
                addSection("Relevant Expertise", skillsText);
            }

            doc.save(`Professional_Resume_${reportData._id?.substring(0, 5) || 'IQ'}.pdf`);
        }
        catch (error) {
            console.log("PDF Error:", error)
            alert("Failed to generate professional PDF. Please try again.")
        }
    }

    return { 
        loading: isReportLoading || isReportsLoading || generateMutation.isPending, 
        report, 
        reports, 
        generateReport: generateMutation.mutateAsync, 
        getReportById: () => {}, // Backward compatibility, query handles fetching automatically
        getReports: () => {}, 
        getResumePdf 
    }
}